apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-config
  namespace: ${ENVIRONMENT}
  labels:
    app: ${APP_NAME}
    environment: ${ENVIRONMENT}
data:
  app.properties: |
    # Application configuration for ${APP_NAME}
    server.port=8080
    logging.level.root=INFO
    management.endpoints.web.exposure.include=health,info,metrics
    
    # Environment-specific settings
    app.environment=${ENVIRONMENT}
    app.name=${APP_NAME}
    
    # Database settings (to be overridden by secrets)
    database.url=jdbc:postgresql://postgres:5432/joinery_${ENVIRONMENT}
    
    # External services
    api.base-url=https://api.${ENVIRONMENT}.joinery.com