name: Build and Push Docker Images

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
        description: 'Application name'
      dockerfile_path:
        required: false
        type: string
        default: './Dockerfile'
        description: 'Path to Dockerfile'
      build_context:
        required: false
        type: string
        default: '.'
        description: 'Build context directory'
      registry_url:
        required: false
        type: string
        default: 'registry.pocketfulofdoom.com'
        description: 'Docker registry URL'
      registry_org:
        required: false
        type: string
        default: ''
        description: 'Docker registry organization/namespace'
    secrets:
      DOCKER_REGISTRY_TOKEN:
        required: true
      DOCKER_REGISTRY_USERNAME:
        required: false
    outputs:
      image_tag:
        description: 'Built image tag'
        value: ${{ jobs.build.outputs.image_tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry_url }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME || 'joinery' }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry_url }}/${{ inputs.registry_org && format('{0}/', inputs.registry_org) || '' }}${{ inputs.app_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max