name: Deploy Joinery Applications

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment to deploy to (dev, staging, prod)'
      app_name:
        required: true
        type: string
        description: 'Application name to deploy'
      image_tag:
        required: false
        type: string
        default: 'latest'
        description: 'Docker image tag to deploy'
    secrets:
      DOCKER_REGISTRY_TOKEN:
        required: true
      KUBE_CONFIG:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout infrastructure repo
        uses: actions/checkout@v4
        with:
          repository: chz160/joinery-infra
          token: ${{ github.token }}
          path: infra
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
      
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
      
      - name: Deploy to Kubernetes
        run: |
          cd infra
          ./scripts/deploy.sh ${{ inputs.app_name }} ${{ inputs.environment }} ${{ inputs.image_tag }}
      
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/${{ inputs.app_name }} -n ${{ inputs.environment }}
          kubectl get pods -n ${{ inputs.environment }} -l app=${{ inputs.app_name }}